#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace ComStubGenerator;

/// <summary>
/// Generates <c>_ReferenceUsings.cs</c> in the output directory so generated
/// reference types are visible globally, similar to VB6 project-wide type visibility.
/// </summary>
public static class ReferenceUsingsGenerator
{
    /// <param name="libraries">All inspected COM libraries.</param>
    /// <param name="outputDir">Destination directory for <c>_ReferenceUsings.cs</c>.</param>
    /// <param name="aliases">
    /// Optional cross-library alias definitions (TKIND_ALIAS) collected via
    /// <see cref="ReferenceStubGenerator.CollectAliases"/>.  Aliases with the same name from
    /// different libraries are deduplicated — the first declaration wins.  This prevents the
    /// CS0105 "using alias appeared previously" error that arises when multiple COM libraries
    /// (e.g. stdole and oleaut32) define the same alias such as <c>OLE_COLOR</c>.
    /// </param>
    public static string Generate(
        IEnumerable<LibraryModel> libraries,
        string outputDir,
        IEnumerable<(string Name, string CSharpType)>? aliases = null,
        bool force = false)
    {
        Directory.CreateDirectory(outputDir);

        var libraryList = libraries?.ToList() ?? [];

        var namespaces = libraryList
            .Select(l => l.SafeName)
            .Where(n => !string.IsNullOrWhiteSpace(n))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();

        var enumTypeUsings = libraryList
            .SelectMany(l => l.Types
                .Where(t => t.Kind == LibraryTypeKind.Enum)
                .Select(t => $"{l.SafeName}.{t.Name}"))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();

        // Deduplicate aliases by name (first declaration wins).
        var seenAliasNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var dedupedAliases = (aliases ?? [])
            .Where(a => !string.IsNullOrWhiteSpace(a.Name) && seenAliasNames.Add(a.Name))
            .ToList();

        string path = Path.Combine(outputDir, "_ReferenceUsings.cs");

        // When not forcing, merge any entries already present in the file so that two
        // successive runs (e.g. x86 then x64) accumulate rather than overwrite.
        if (!force && File.Exists(path)) {
            foreach (var line in File.ReadAllLines(path)) {
                string trimmed = line.Trim();
                if (!trimmed.StartsWith("global using ", StringComparison.Ordinal)) continue;

                string body = trimmed["global using ".Length..].TrimEnd(';');

                if (body.StartsWith("static ", StringComparison.Ordinal)) {
                    string enumType = body["static ".Length..].Trim();
                    if (!enumTypeUsings.Contains(enumType, StringComparer.OrdinalIgnoreCase))
                        enumTypeUsings.Add(enumType);
                } else {
                    int eqIdx = body.IndexOf(" = ", StringComparison.Ordinal);
                    if (eqIdx >= 0) {
                        string aliasName = body[..eqIdx].Trim();
                        string aliasType = body[(eqIdx + 3)..].Trim();
                        if (seenAliasNames.Add(aliasName))
                            dedupedAliases.Add((aliasName, aliasType));
                    } else {
                        string ns = body.Trim();
                        if (!namespaces.Contains(ns, StringComparer.OrdinalIgnoreCase))
                            namespaces.Add(ns);
                    }
                }
            }
        }

        namespaces = namespaces
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(n => n, StringComparer.OrdinalIgnoreCase)
            .ToList();

        enumTypeUsings = enumTypeUsings
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(n => n, StringComparer.OrdinalIgnoreCase)
            .ToList();

        dedupedAliases = dedupedAliases
            .OrderBy(a => a.Name, StringComparer.OrdinalIgnoreCase)
            .ToList();

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        foreach (var ns in namespaces) {
            builder.AppendLine($"global using {ns};");
        }

        if (namespaces.Count > 0 && (enumTypeUsings.Count > 0 || dedupedAliases.Count > 0)) {
            builder.AppendLine();
        }

        foreach (var enumType in enumTypeUsings) {
            builder.AppendLine($"global using static {enumType};");
        }

        if (dedupedAliases.Count > 0) {
            if (enumTypeUsings.Count > 0) builder.AppendLine();
            foreach (var (name, csType) in dedupedAliases) {
                builder.AppendLine($"global using {name} = {csType};");
            }
        }

        File.WriteAllText(path, builder.ToString());

        return path;
    }
}
