#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace VB6Converter.ReferenceStubs;

/// <summary>
/// Generates <c>_ReferenceUsings.cs</c> in the output directory so generated
/// reference types are visible globally, similar to VB6 project-wide type visibility.
/// </summary>
public static class ReferenceUsingsGenerator
{
    /// <param name="libraries">All inspected COM libraries.</param>
    /// <param name="outputDir">Destination directory for <c>_ReferenceUsings.cs</c>.</param>
    /// <param name="aliases">
    /// Optional cross-library alias definitions (TKIND_ALIAS) collected via
    /// <see cref="ReferenceStubGenerator.CollectAliases"/>.  Aliases with the same name from
    /// different libraries are deduplicated — the first declaration wins.  This prevents the
    /// CS0105 "using alias appeared previously" error that arises when multiple COM libraries
    /// (e.g. stdole and oleaut32) define the same alias such as <c>OLE_COLOR</c>.
    /// </param>
    public static string Generate(
        IEnumerable<LibraryModel> libraries,
        string outputDir,
        IEnumerable<(string Name, string CSharpType)>? aliases = null)
    {
        Directory.CreateDirectory(outputDir);

        var libraryList = libraries?.ToList() ?? [];

        var namespaces = libraryList
            .Select(l => l.SafeName)
            .Where(n => !string.IsNullOrWhiteSpace(n))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(n => n, StringComparer.OrdinalIgnoreCase)
            .ToList();

        var enumTypeUsings = libraryList
            .SelectMany(l => l.Types
                .Where(t => t.Kind == LibraryTypeKind.Enum)
                .Select(t => $"{l.SafeName}.{t.Name}"))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(n => n, StringComparer.OrdinalIgnoreCase)
            .ToList();

        // Deduplicate aliases by name (first declaration wins).
        var seenAliasNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var dedupedAliases = (aliases ?? [])
            .Where(a => !string.IsNullOrWhiteSpace(a.Name) && seenAliasNames.Add(a.Name))
            .OrderBy(a => a.Name, StringComparer.OrdinalIgnoreCase)
            .ToList();

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        foreach (var ns in namespaces) {
            builder.AppendLine($"global using {ns};");
        }

        if (namespaces.Count > 0 && (enumTypeUsings.Count > 0 || dedupedAliases.Count > 0)) {
            builder.AppendLine();
        }

        foreach (var enumType in enumTypeUsings) {
            builder.AppendLine($"global using static {enumType};");
        }

        if (dedupedAliases.Count > 0) {
            if (enumTypeUsings.Count > 0) builder.AppendLine();
            foreach (var (name, csType) in dedupedAliases) {
                builder.AppendLine($"global using {name} = {csType};");
            }
        }

        string path = Path.Combine(outputDir, "_ReferenceUsings.cs");
        File.WriteAllText(path, builder.ToString());

        return path;
    }
}
